"""initial

Revision ID: 9db8a209a651
Revises: 7137051ec8df
Create Date: 2026-02-27 09:01:55.705815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db8a209a651'
down_revision: Union[str, Sequence[str], None] = '7137051ec8df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'locale',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'locale',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
