from aiogram.utils.i18n import lazy_gettext as __

MY_REFERRALS = __("My Referrals 📋")
HELP = __("HELP 📨")
CATEGORIES = __("Categories 📦")
SETTINGS = __("Settings ⚙️")
WELCOME_TEXT = __("Welcome to our bot!😊")
ADMIN = __("ADMIN🧑‍💼")
BACK_TEXT = __("⏮️ Back")
MY_CART = __("My cart 🛒")
ADD_CATG = __("Add category")
SHOW_CATG = __("Show categories")
SHOW_PRODUCT = __("Show products")
ADD_PRODUCT = __("Add product")
CHANGE_LANG = __("Change language 🇬🇧 🇺🇿")
NOTIF = __("Notification 📢")
